export const QUESTIONS = {
    // QUESTION_GET_ALL: "QUESTION_GET_ALL",
    // QUESTION_DETAIL: "QUESTION_DETAIL",
    // QUESTION_ADD: "QUESTION_ADD",
    // QUESTION_ANSWER: "QUESTION_ANSWER"
    QUESTION_GET_ALL: {
        REQUEST: 'QUESTION_GET_ALL_REQUEST',
        SUCCESS: 'QUESTION_GET_ALL_SUCCESS',
        ERROR: 'QUESTION_GET_ALL_ERROR',
    }
};
