export const QUESTIONS = {
    QUESTION_GET_ALL: {
        REQUEST: 'QUESTION_GET_ALL_REQUEST',
        SUCCESS: 'QUESTION_GET_ALL_SUCCESS',
        ERROR: 'QUESTION_GET_ALL_ERROR',
    },
    GET_QUESTION_DETAILS: {
        REQUEST: 'GET_QUESTION_DETAILS_REQUEST',
        SUCCESS: 'GET_QUESTION_DETAILS_SUCCESS',
        ERROR: 'GET_QUESTION_DETAILS_ERROR',
    },
    SUBMIT_NEW_QUESTION: {
        REQUEST: 'SUBMIT_NEW_QUESTION_REQUEST',
        SUCCESS: 'SUBMIT_NEW_QUESTION_SUCCESS',
        ERROR: 'SUBMIT_NEW_QUESTION_ERROR',
    }
};
